# Generated by Django 4.1 on 2023-06-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=100)),
                ('precio_prod', models.IntegerField()),
                ('stock_prod', models.IntegerField()),
                ('desc_prod', models.CharField(max_length=100)),
                ('fecha_prod', models.DateField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaPapercute.categoria')),
            ],
        ),
    ]
