# Generated by Django 4.1 on 2023-06-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaPapercute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
