# Generated by Django 4.1 on 2023-06-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaPapercute', '0004_comuna_region_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_categoria',
            new_name='id_cat',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='img_url',
            new_name='img_prod',
        ),
    ]
