# Generated by Django 4.1 on 2023-06-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaPapercute', '0005_rename_id_categoria_producto_id_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_prod',
            field=models.ImageField(upload_to='prodImagenes'),
        ),
    ]
