# Generated by Django 4.1 on 2023-06-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaPapercute', '0006_alter_producto_img_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='desc_prod',
        ),
    ]
